name: Markdown Validation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    name: Check Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md